name: Build Example Apps and Run Tests

on:
  push:
    branches:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Checkout Submodules
      uses: actions/checkout@v3
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build Example App - ViewBinding
      run: ./gradlew :example-viewbinding:assembleRelease

    - name: Run Lint
      run: ./gradlew lint --console plain
    - name: Run Unit Tests
      run: ./gradlew test --console plain
